### ISSUE TITLE
Error running locally

### ISSUE THREAD

**Issue by danipralea** [pdfplum/pdfplum#32]
### Description

First of all, thank you for having implemented this extension! 🤗 

I receive a (timeout) error when trying to generate a document with the extension installed locally
It goes well when I run the cloud one though.
I am using the sample template for both. And again, for both I use the exact same params
```
{
    "data": {
        "companyName": "My Company",
        "date": "26-03-2024",
        "invoiceId": "1234",
        "billContactName": "Client Name",
        "billClientCompany": "Billing Company",
        "billAddress": "California",
        "billPhone": "abc",
        "billEmail": "client@email.com",
        "shipNameOrDept": "Client",
        "shipClientCompany": "Name",
        "shipAddress": "City, State/Country, ZIP Code",
        "shipPhone": "+123456789",
        "rows": [
            {
                "description": "Development services",
                "quantity": 160,
                "unitPrice": 50
            }
        ],
        "discount": 15,
        "taxRate": 5
    },
    "outputStoragePrefix": "invoices/",
    "outputFileName": "abc.pdf",
    "returnPdfInResponse": true
}
```
[template.zip](https://github.com/pdfplum/pdfplum/files/14849203/template.zip)

Locally:
![image](https://github.com/pdfplum/pdfplum/assets/768893/2a8b95b2-0077-4c56-85da-e6380ec3e77a)
Settings:

```ADJUST_HEIGHT_TO_FIT=no
CHROMIUM_PDF_OPTIONS={}
firebaseextensions.v1beta.function/location=europe-central2
NETWORK_IDLE_TIME=5000
OUTPUT_STORAGE_BUCKET=parhelion-admin.appspot.com
RETURN_PDF_IN_RESPONSE=no
SHOULD_MAKE_PDF_PUBLIC=no
SHOULD_WAIT_FOR_IS_READY=no
TEMPLATE_PATH=parhelion-admin.appspot.com/template
```

Cloud:
![image](https://github.com/pdfplum/pdfplum/assets/768893/9c5e543b-787d-41be-9c67-6751aec339b0)
Settings:
![image](https://github.com/pdfplum/pdfplum/assets/768893/15e4afb6-da6c-4816-ac7e-a58db41188c9)

### Steps to reproduce the behavior

Install the extension locally and run with the same template and params as the cloud one

### Logs

```
i  functions: Beginning execution of "europe-central2-ext-http-pdf-generator-executePdfGenerator"
>  {"severity":"INFO","message":"Running action 'parse parameters'"}
>  parhelion-admin.appspot.com/template {
>    data: {
>      companyName: 'My Company',
>      date: '26-03-2024',
>      invoiceId: '1234',
>      billContactName: 'Client Name',
>      billClientCompany: 'Billing Company',
>      billAddress: 'California',
>      billPhone: 'abc',
>      billEmail: 'client@email.com',
>      shipNameOrDept: 'Client',
>      shipClientCompany: 'Name',
>      shipAddress: 'City, State/Country, ZIP Code',
>      shipPhone: '+123456789',
>      rows: [ [Object] ],
>      discount: 15,
>      taxRate: 5
>    },
>    outputStoragePrefix: 'invoices/',
>    outputFileName: 'abc.pdf',
>    returnPdfInResponse: true
>  } undefined object
>  {"severity":"INFO","message":"Action 'parse parameters' finished successfully"}
>  {"adjustHeightToFit":false,"chromiumPdfOptions":{},"data":{"companyName":"My Company","date":"26-03-2024","invoiceId":"1234","billContactName":"Client Name","billClientCompany":"Billing Company","billAddress":"California","billPhone":"abc","billEmail":"client@email.com","shipNameOrDept":"Client","shipClientCompany":"Name","shipAddress":"City, State/Country, ZIP Code","shipPhone":"+123456789","rows":[{"description":"Development services","quantity":160,"unitPrice":50}],"discount":15,"taxRate":5},"headless":true,"outputStorageBucket":"parhelion-admin.appspot.com","outputStoragePrefix":"invoices/","outputFileName":"abc.pdf","returnPdfInResponse":true,"templateBucket":"parhelion-admin.appspot.com","templatePrefix":"","templateId":"template","networkIdleTime":5000,"shouldWaitForIsReady":true,"severity":"INFO","message":"Parameters"}
>  {"severity":"INFO","message":"Running action 'produce pdf'"}
>  {"severity":"INFO","message":"Running action 'load template'"}
>  {"relativePath":"/index.html","severity":"INFO","message":"Processing file with handlebars"}
>  {"relativePath":"/styles.css","severity":"INFO","message":"Copying file as is"}
>  {"severity":"INFO","message":"Action 'load template' finished successfully"}
>  {"severity":"INFO","message":"Running action 'serve template'"}
>  {"severity":"INFO","message":"Action 'serve template' finished successfully"}
>  {"severity":"INFO","message":"Running action 'render pdf'"}
i  Your function timed out after ~60s. To configure this timeout, see
      https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation.
i  Request to function failed: Error: socket hang up
>  {"severity":"ERROR","message":"Error ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.\n    at /Users/danutpralea/.cache/firebase/extensions/pdfplum/http-pdf-generator@0.17.1/functions/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/danutpralea/.cache/firebase/extensions/pdfplum/http-pdf-generator@0.17.1/functions/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/danutpralea/.cache/firebase/extensions/pdfplum/http-pdf-generator@0.17.1/functions/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async JSHandle.evaluateHandle (/Users/danutpralea/.cache/firebase/extensions/pdfplum/http-pdf-generator@0.17.1/functions/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:97:16)\n    at async WaitTask.rerun (/Users/danutpralea/.cache/firebase/extensions/pdfplum/http-pdf-generator@0.17.1/functions/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:114:28) {\n  originalMessage: ''\n}"}
>  {"severity":"ERROR","message":"ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.\n    at /Users/danutpralea/.cache/firebase/extensions/pdfplum/http-pdf-generator@0.17.1/functions/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/danutpralea/.cache/firebase/extensions/pdfplum/http-pdf-generator@0.17.1/functions/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/danutpralea/.cache/firebase/extensions/pdfplum/http-pdf-generator@0.17.1/functions/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async JSHandle.evaluateHandle (/Users/danutpralea/.cache/firebase/extensions/pdfplum/http-pdf-generator@0.17.1/functions/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:97:16)\n    at async WaitTask.rerun (/Users/danutpralea/.cache/firebase/extensions/pdfplum/http-pdf-generator@0.17.1/functions/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:114:28) {\n  originalMessage: ''\n}"}
```

**Comment by sassanh** [comment]
@danipralea Sorry for the late response, I was busy these weeks. Did you find a way to make it work for you?

**Comment by danipralea** [comment]
@sassanh thank you for you reply. Yes, I actually did. no idea how tbh, but I found a few other issues. Is it ok if I send you and email at hi@pdfplum.com or should I post it here?

**Comment by sassanh** [comment]
Both work for me, but if you create issues here it has the benefit that others can see them too and we can take advantage of GitHub’s issue tracking.
