### ISSUE TITLE
'ApiError' after installing firestore-pdf-generator extension (0.12.18-rc.3) via Firebase Console

### ISSUE THREAD

**Issue by fyimail** [pdfplum/pdfplum#9]
When installing firestore-pdf-generator from the following link...

> You can use this link: https://console.firebase.google.com/project/_/extensions/install?ref=pdfplum/firestore-pdf-generator@0.12.18-rc.3

...I first noticed the following instruction under "How this extension works" which seemed unexpected:
<img width="514" alt="firestore-error01" src="https://github.com/pdfplum/pdfplum/assets/7285433/0c85d5b7-dd73-4060-86ea-3e9aa7790bbd">

And then the logs showed the following error message:
```
textPayload: "Error ApiError: No such object: temp-rh-app.appspot.com/template
    at new ApiError (/workspace/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:79:15)
    at Util.parseHttpRespMessage (/workspace/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:181:41)
    at Util.handleResp (/workspace/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:155:76)
    at Duplexify.<anonymous> (/workspace/node_modules/@google-cloud/storage/build/src/file.js:1072:38)
    at Duplexify.emit (node:events:513:28)
    at Duplexify.emit (node:domain:552:15)
    at PassThrough.emit (node:events:513:28)
    at PassThrough.emit (node:domain:552:15)
    at onResponse (/workspace/node_modules/retry-request/index.js:234:19)
    at PassThrough.<anonymous> (/workspace/node_modules/retry-request/index.js:165:11) {
  code: 404,
  errors: [],
  response: <ref *1> PassThrough {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: false,
      ended: true,
      endEmitted: true,
      reading: false,
      constructed: true,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: true,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: true
    },
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      error: [Array],
      readable: [Function: next],
      end: [Array],
      close: [Array],
      finish: [Function: onfinish]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: true,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: true,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      [Symbol(kOnFinished)]: []
    },
    allowHalfOpen: true,
    statusCode: 404,
    statusMessage: 'Not Found',
    request: {
      agent: [Agent],
      headers: [Object],
      href: 'https://storage.googleapis.com/storage/v1/b/temp-rh-app.appspot.com/o/template?alt=media'
    },
    body: [Circular *1],
    headers: {
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
      'cache-control': 'private, max-age=0',
      'content-length': '48',
      'content-type': 'text/html; charset=UTF-8',
      date: 'Wed, 17 May 2023 11:23:53 GMT',
      expires: 'Wed, 17 May 2023 11:23:53 GMT',
      server: 'UploadServer',
      vary: 'Origin, X-Origin',
      'x-guploader-uploadid': 'ADPycdtA5aItomMX1Cvaf4aeJbZ8qbioj_fP2GVwuTaopEIjbU5c2XdoOV2ZfsVvAHKeCL03-7nqWgUxzfzEPsO9O8kOCA'
    },
    toJSON: [Function: toJSON],
    [Symbol(kCapture)]: false,
    [Symbol(kCallback)]: null
  }
}"
timestamp: "2023-05-17T11:23:53.463850Z"
trace: "projects/temp-rh-app/traces/75e71b5a3015e3e027651760ce9cec40"
}
```

**Comment by sassanh** [comment]
Thanks for reporting this, I will update the docs, the correct version would be:

```
Download demo.zip from here, rename it to `template` and upload it into bucket temp-rh-app.appspot.com.
```

Alternatively you can set the filename to `template.zip` instead of `template` if it makes more sense in your setup.

If you put the template in the bucket, you shouldn't get the error you mentioned above.

**Comment by fyimail** [comment]
Thanks for the update. So I downloaded demo.zip and renamed it to 'template' but it resulted in this error:

`There must be an 'index.html' file inside the zip file in its root folder.`

The reason is because when I open demo.zip, there was another folder called 'demo' so I renamed this folder to 'template' and compressed it into 'template.zip'. But after this resolution...I'm not getting another error:

```
Error Error: Lexical error on line 1. Unrecognized text.
Mac OS X    
^
    at Parser.parseError (/workspace/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:267:19)
    at Object.parseError (/workspace/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:394:36)
    at Object.next (/workspace/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:522:33)
    at Object.lex (/workspace/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:526:30)
    at lex (/workspace/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:297:36)
    at Parser.parse (/workspace/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:320:34)
    at parseWithoutProcessing (/workspace/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:33)
    at HandlebarsEnvironment.parse (/workspace/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:52:13)
    at compileInput (/workspace/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:508:19)
    at ret (/workspace/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:517:18)
```

Can you recommend how I can resolve this?

**Comment by sassanh** [comment]
You are right, it didn't work because the name of the directory in the zip file did not match with the filename of the zip file. I tried to take care of this issue in the latest rc. I also tried to ignore mac os files, it would be nice if you could check the template.zip file that caused the Lexical error again with this new version so that we can make sure it is ignoring the mac os files.

You can download the latest rcs from here:
https://console.firebase.google.com/project/_/extensions/install?ref=pdfplum/firestore-pdf-generator@0.12.19-rc.0
https://console.firebase.google.com/project/_/extensions/install?ref=pdfplum/http-pdf-generator@0.12.19-rc.0

**Comment by sassanh** [comment]
I assume this issue is resolved, please inform me if it's not the case.
